services:
  - type: docker
    name: laravel-app
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: APP_URL
        value: https://papamalick.teuw.com

  - type: pserv
    name: postgres-db
    runtime: postgres
    version: "15"
    disk:
      name: postgres-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 20